### ISSUE TITLE
Wont install on ubuntu 20.04

### ISSUE THREAD

**Issue by Jarco-dev** [adnanrahic/node-gcstats#5]
I am unable to install the module on ubuntu 20.04, is there any way I can fix this or that this can be fixed?
Below the error log i encountered while trying to install it

```
447 error code 1
448 error path /home/container/node_modules/@sematext/gc-stats
449 error command failed
450 error command sh -c node-pre-gyp install --fallback-to-build
451 error Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/container/node_modules/@sematext/gc-stats/build/gcstats/v1.5.4/Release/node-v93-linux-x64-glibc/gcstats.node --module_name=gcstats --module_path=/home/container/node_modules/@sematext/gc-stats/build/gcstats/v1.5.4/Release/node-v93-linux-x64-glibc --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
452 error node-pre-gyp info it worked if it ends with ok
452 error node-pre-gyp info using node-pre-gyp@0.15.0
452 error node-pre-gyp info using node@16.9.1 | linux | x64
452 error node-pre-gyp WARN Using needle for node-pre-gyp https download
452 error node-pre-gyp info check checked for "/home/container/node_modules/@sematext/gc-stats/build/gcstats/v1.5.4/Release/node-v93-linux-x64-glibc/gcstats.node" (not found)
452 error node-pre-gyp http GET https://github.com/adnanrahic/node-gcstats/releases/download/1.5.4/gcstats/v1.5.4/Release/node-v93-linux-x64-glibc.tar.gz
452 error node-pre-gyp http 404 https://github.com/adnanrahic/node-gcstats/releases/download/1.5.4/gcstats/v1.5.4/Release/node-v93-linux-x64-glibc.tar.gz
452 error node-pre-gyp WARN Tried to download(404): https://github.com/adnanrahic/node-gcstats/releases/download/1.5.4/gcstats/v1.5.4/Release/node-v93-linux-x64-glibc.tar.gz
452 error node-pre-gyp WARN Pre-built binaries not found for @sematext/gc-stats@1.5.4 and node@16.9.1 (node-v93 ABI, glibc) (falling back to source compile with node-gyp)
452 error node-pre-gyp http 404 status code downloading tarball https://github.com/adnanrahic/node-gcstats/releases/download/1.5.4/gcstats/v1.5.4/Release/node-v93-linux-x64-glibc.tar.gz
452 error gyp info it worked if it ends with ok
452 error gyp info using node-gyp@7.1.2
452 error gyp info using node@16.9.1 | linux | x64
452 error gyp info ok
452 error gyp info it worked if it ends with ok
452 error gyp info using node-gyp@7.1.2
452 error gyp info using node@16.9.1 | linux | x64
452 error gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"
452 error gyp http GET https://nodejs.org/download/release/v16.9.1/node-v16.9.1-headers.tar.gz
452 error gyp http 200 https://nodejs.org/download/release/v16.9.1/node-v16.9.1-headers.tar.gz
452 error gyp http GET https://nodejs.org/download/release/v16.9.1/SHASUMS256.txt
452 error gyp http 200 https://nodejs.org/download/release/v16.9.1/SHASUMS256.txt
452 error (node:52) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
452 error (Use `node --trace-deprecation ...` to show where the warning was created)
452 error gyp info spawn /usr/bin/python3
452 error gyp info spawn args [
452 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
452 error gyp info spawn args   'binding.gyp',
452 error gyp info spawn args   '-f',
452 error gyp info spawn args   'make',
452 error gyp info spawn args   '-I',
452 error gyp info spawn args   '/home/container/node_modules/@sematext/gc-stats/build/config.gypi',
452 error gyp info spawn args   '-I',
452 error gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
452 error gyp info spawn args   '-I',
452 error gyp info spawn args   '/home/container/.cache/node-gyp/16.9.1/include/node/common.gypi',
452 error gyp info spawn args   '-Dlibrary=shared_library',
452 error gyp info spawn args   '-Dvisibility=default',
452 error gyp info spawn args   '-Dnode_root_dir=/home/container/.cache/node-gyp/16.9.1',
452 error gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
452 error gyp info spawn args   '-Dnode_lib_file=/home/container/.cache/node-gyp/16.9.1/<(target_arch)/node.lib',
452 error gyp info spawn args   '-Dmodule_root_dir=/home/container/node_modules/@sematext/gc-stats',
452 error gyp info spawn args   '-Dnode_engine=v8',
452 error gyp info spawn args   '--depth=.',
452 error gyp info spawn args   '--no-parallel',
452 error gyp info spawn args   '--generator-output',
452 error gyp info spawn args   'build',
452 error gyp info spawn args   '-Goutput_dir=.'
452 error gyp info spawn args ]
452 error gyp info ok
452 error gyp info it worked if it ends with ok
452 error gyp info using node-gyp@7.1.2
452 error gyp info using node@16.9.1 | linux | x64
452 error gyp ERR! build error
452 error gyp ERR! stack Error: not found: make
452 error gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:10:17)
452 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:18
452 error gyp ERR! stack     at new Promise (<anonymous>)
452 error gyp ERR! stack     at step (/usr/local/lib/node_modules/npm/node_modules/which/which.js:54:21)
452 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:71:22
452 error gyp ERR! stack     at new Promise (<anonymous>)
452 error gyp ERR! stack     at subStep (/usr/local/lib/node_modules/npm/node_modules/which/which.js:69:33)
452 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:80:22
452 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
452 error gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
452 error gyp ERR! System Linux 5.4.0-84-generic
452 error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/container/node_modules/@sematext/gc-stats/build/gcstats/v1.5.4/Release/node-v93-linux-x64-glibc/gcstats.node" "--module_name=gcstats" "--module_path=/home/container/node_modules/@sematext/gc-stats/build/gcstats/v1.5.4/Release/node-v93-linux-x64-glibc" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
452 error gyp ERR! cwd /home/container/node_modules/@sematext/gc-stats
452 error gyp ERR! node -v v16.9.1
452 error gyp ERR! node-gyp -v v7.1.2
452 error gyp ERR! not ok
452 error node-pre-gyp ERR! build error
452 error node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/container/node_modules/@sematext/gc-stats/build/gcstats/v1.5.4/Release/node-v93-linux-x64-glibc/gcstats.node --module_name=gcstats --module_path=/home/container/node_modules/@sematext/gc-stats/build/gcstats/v1.5.4/Release/node-v93-linux-x64-glibc --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
452 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/container/node_modules/@sematext/gc-stats/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
452 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
452 error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
452 error node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
452 error node-pre-gyp ERR! System Linux 5.4.0-84-generic
452 error node-pre-gyp ERR! command "/usr/local/bin/node" "/home/container/node_modules/@sematext/gc-stats/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
452 error node-pre-gyp ERR! cwd /home/container/node_modules/@sematext/gc-stats
452 error node-pre-gyp ERR! node -v v16.9.1
452 error node-pre-gyp ERR! node-pre-gyp -v v0.15.0
452 error node-pre-gyp ERR! not ok
```

**Comment by Jarco-dev** [comment]
Seems to have been a issue to do with the docker image i was using inside my pterodactyl egg
